### ISSUE TITLE
Error when using Routify on a templated project

### ISSUE THREAD

**Issue by jdkdev** [roxiness/routify#60] opened 2020-01-12 16:07 UTC
Thanks for any help in advance

## Issue
Error when using Routify on a templated project, it always errors out when trying to create the `pages` directory that already exists in my src directory

If I comment the line out that tries to make it in `/lib/services/monitor.js:20:6`, everything works fine.  I assume it should gracefully fail, but why would it not for me?

### Error when running `routify`
```
fs.js:885
  return binding.mkdir(pathModule._makeLong(path),
^

Error: EEXIST: file already exists, mkdir '/home/j/code/tmp/newappy/src/pages'
at Object.fs.mkdirSync (fs.js:885:18)
at monitor (/home/j/code/tmp/newappy/node_modules/@sveltech/routify/lib/services/monitor.js:20:6)
at start (/home/j/code/tmp/newappy/node_modules/@sveltech/routify/lib/services/interface.js:34:34)
at Object.<anonymous> (/home/j/code/tmp/newappy/node_modules/@sveltech/routify/plugins/cli.js:25:1)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Function.Module.runMain (module.js:694:10)
```

**Comment by jakobrosenberg** [comment] 2020-01-12 16:10
This is mostly likely caused by running either an old version of Node or Routify. Do you know which version of Routify you're on?

**Comment by jdkdev** [comment] 2020-01-12 19:26
Yes! Thank you, I updated my node and reinstalled routify and I am all set!

Thank you Jakob.  And thanks for making Routify. I really like using it so far.

**Comment by jakobrosenberg** [comment] 2020-01-12 19:28
Happy to help. 😄

Closing this issue as it has been solved.

**Closed as completed by jakobrosenberg** 2020-01-12 19:28 UTC
