### ISSUE TITLE
Redundant <span> tags in the DOM structure

### ISSUE THREAD

**Issue by fbele** [roxiness/routify#352] opened 2021-03-22 17:27 UTC
Hi

It's not really an issue but I would just like to understand where the additional redundant `<span>` tags in the structure are coming from.

If you take a look at the official [Blog example](https://blog-example.routify.dev/), you can see that the DOM structure is as expect, that is there are no extra `<span>` tags:
![image](https://user-images.githubusercontent.com/33025896/112031388-912e6400-8b3b-11eb-9502-5acbb002b4d8.png)

But then I cloned this same project to my local environment and just runned it and this extra <span> tags appear in the DOM structure:
![image](https://user-images.githubusercontent.com/33025896/112031678-e2d6ee80-8b3b-11eb-9195-b19d0627a915.png)

I can observe this also in my own project. The `<span>` tags appear in each root of the Route.
Does anybody know why is that and how can one remove them?

Thanks.

Regards,
Franc

**Comment by ghostdevv** [comment] 2021-03-22 20:33
Duplicate of #347

**Closed as completed by ghostdevv** 2021-03-22 20:33 UTC
Labels: duplicate

**Comment by fbele** [comment] 2021-03-22 20:41
> Duplicate of #347

I understand, it's a duplicate issue.

However it doesn't really resolve the issue. Why are the spans not appearing in the official example site, but they are when I'm compiling and running the exact same source code?
What and where is the difference?

I would just like to know what to do in order to remove them?

**Comment by ghostdevv** [comment] 2021-03-22 20:42
@jakobrosenberg

**Comment by jakobrosenberg** [comment] 2021-03-22 20:46
The `span` is used to detect the parent element of a layout or page.
https://github.com/roxiness/routify/issues/347#issuecomment-793040887

Let's continue this conversation in the original thread.
