### ISSUE TITLE
`singleBuild: true` doesn't work for me

### ISSUE THREAD

**Issue by akauppi** [roxiness/routify#73] opened 2020-01-24 20:09 UTC
In [svg.rx.js-demo](https://github.com/akauppi/svg.rx.js-demo/) project, I'm unable to just build the pages, using Routify.

```
$ npm run build

> svg.rx.js-demo@ build /Users/asko/Git/svg.rx.js-demo
> PROD=true rollup -c

[!] TypeError: Cannot destructure property 'waitIdle' of 'start(...)' as it is undefined.
TypeError: Cannot destructure property 'waitIdle' of 'start(...)' as it is undefined.
    at Object.svelteFileRouter [as routify] (/Users/asko/Git/svg.rx.js-demo/node_modules/@sveltech/routify/plugins/rollup.js:5:11)
    at Object.<anonymous> (/Users/asko/Git/svg.rx.js-demo/rollup.config.js:44:21)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.require.extensions.<computed> [as .js] (/Users/asko/Git/svg.rx.js-demo/node_modules/rollup/dist/bin/rollup:831:24)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Users/asko/Git/svg.rx.js-demo/node_modules/rollup/dist/bin/rollup:838:32

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svg.rx.js-demo@ build: `PROD=true rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svg.rx.js-demo@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asko/.npm/_logs/2020-01-24T20_03_53_176Z-debug.log
```

It looks like a Routify bug, for me. Is this reproducible for others - should `singleBuild` option work? Using `1.0.1-38`.

**Comment by jakobrosenberg** [comment] 2020-01-24 20:40
Single build should be working. I've been using it all day. It's hard to tell from your code what the issue is. I couldn't open the link.

**Comment by akauppi** [comment] 2020-01-24 21:05
Sorry - the repo had remained private for no reason. Now public.

**Comment by jakobrosenberg** [comment] 2020-01-25 12:33
I just cloned it and except for having to ``npm i ncp``, it was working fine.

I don't recognize anything from the logs and AFAIR, we have no ``waitIdle``.

Could you try isolate Routify with ``"build:routify": "routify -b"``and see if it gives you any errors?

**Comment by akauppi** [comment] 2020-01-25 18:14
I think it's connected to these lines: https://github.com/sveltech/routify/blob/master/lib/services/interface.js#L64-L73

I tried locally to make the function return `{}` if `watch` is false, and it seems to work (i.e. build succeeds). I cannot say if it's the "right" fix, though.

**Comment by quentincaffeino** [comment] 2020-01-28 15:30
Not exactly the same but guess it is related: https://gitlab.com/vinnyujezd/front-old/commit/435c1c978a5496691ed01de9a52d5ba9b68d2703

```
[!] (plugin @sveltech/routify) TypeError: waitIdle is not a function
TypeError: waitIdle is not a function
    at Object.renderStart (/app/node_modules/@sveltech/routify/plugins/rollup.js:19:13)
    at /app/node_modules/rollup/dist/shared/node-entry.js:13096:25
    at async Promise.all (index 0)
```

For now fixed with:
```
# package.json
"scripts": {
  "build": "npm-run-all -s routify:build rollup:build",
  "rollup:build": "rollup -c",
  "routify:build": "routify -b"
}
```
```
# rollup.config.js
...
plugins: [
...
!production && routify({ // (plugin @sveltech/routify) TypeError: waitIdle is not a function
	debug: !production,
	singleBuild: production
}),
...
]
...
```

**Comment by jakobrosenberg** [comment] 2020-01-28 16:26
@QuentinCaffeino Could you update to the latest release and see if this still an issue?

@akauppi Apologies for not getting back to you sooner. I thought I'd fixed this, but forgotten to let you know.

**Comment by quentincaffeino** [comment] 2020-01-28 19:29
@jakobrosenberg still got same error on `@sveltech/routify@1.0.1-43`

**Comment by jakobrosenberg** [comment] 2020-01-29 09:56
@QuentinCaffeino @akauppi This should be finally be fixed. Sorry for the inconvenience.

**Closed as completed** 2020-01-30 17:54 UTC
