### ISSUE TITLE
When using $url in _layout.svelte that isn't in the root

### ISSUE THREAD

**Issue by MirrorBytes** [roxiness/routify#274] opened 2020-09-21 17:37 UTC
**bug description**
It always returns the index path of the directory.

Have directory named ```form```, I have an ```index.svelte``` file and a ```add``` directory which contains a ```_layout.svelte``` file along with ```index.svelte``` and ```builder.svelte```. When I try going to ```/form/add/builder```, $url() returns ```/form/add``` when the function is called in ```_layout.svelte```.

**version**
Routify: ^2.1.3
Svelte : ^3.24.0

**screenshot**
![Screenshot 2020-09-21 133610](https://user-images.githubusercontent.com/22119469/93801106-84be6280-fc0f-11ea-8037-ab6f76aa782e.png)
![Screenshot 2020-09-21 133645](https://user-images.githubusercontent.com/22119469/93801103-84be6280-fc0f-11ea-8115-505b80a7dbef.png)

**Comment by jakobrosenberg** [comment] 2020-09-21 17:42
`$url()` should always return the index of the parent folder when called from a layout. I can't tell what the issue is. Could you explain what you're trying to accomplish?

**Comment by MirrorBytes** [comment] 2020-09-21 18:03
It should? That seems like a bug to me. Can't argue with intended functionality though.

I'm trying to use the url as a stepper for a multi-step form. So in the case of going to ```/form/add``` it would be step 1, ```/form/add/builder``` step 2.

I could probably just grab the location.

**Comment by MirrorBytes** [comment] 2020-09-21 18:12
"$url resolves paths relative to the page/layout file in which it is used. This ensures consistent URLs which are unaffected by the current browser address (unlike normal relative URLs)."

I'm assuming this is the line in the docs I should have read more carefully.
Still, it just doesn't feel correct. I'd assume it to function in reflection of the current browser address... as most routing systems (including Sapper's) do. This means building new functionality outside the library to track the current browser address.

Also, this would effectively break the $url() call inside an anchor tag. As it resolves to relative pathing (even with an absolute path provided) in the case of a layout being used.

**Comment by jakobrosenberg** [comment] 2020-09-21 18:23
URLs relative to the current address are nearly useless. The relative filepath is static and reliable whereas native relative URLs are volatile.

```html
<!-- form/add/_layout.svelte -->

<a href={ $url('./builder') }>reliable link</a>

<a href="./builder" use:$url >reliable link</a>

<a href="./builder">unreliable link</a>
```

The links using the helper will always point to '/form/add/builder'.

The link using native relative path will only work on `/form/add/`. If your current address changes to `/form/add` or `/form/add/popup/` your link will break.

**Comment by MirrorBytes** [comment] 2020-09-21 18:37
That's not my point. In terms of using absolute paths in the $url() function, it won't update the layout based on the current path.

Do I have to pass the current path, say ```/form/add/builder``` back to the layout component in order to update other components being used in the layout? Should I use location.pathname instead?

**Comment by jakobrosenberg** [comment] 2020-09-21 18:44
I can't tell what you're trying to do.

Could you give me a code example with comments of what you expect/want?

EDIT: `$page.path` might be what you're looking for.

**Comment by MirrorBytes** [comment] 2020-09-21 18:58
File layout
```
pages
    _layout.svelte
    index.svelte
    form
        view.svelte
        add
            _layout.svelte
            index.svelte
            builder.svelte
```

I'd like for the layout in 'pages/form/add' to be able to access the current path so it can tell whether it's on the index or builder.

As for $page.path:
![Screenshot 2020-09-21 145811](https://user-images.githubusercontent.com/22119469/93809120-e59f6800-fc1a-11ea-82ca-efe8766778b0.png)

**Comment by jakobrosenberg** [comment] 2020-09-21 19:01
You need
```javascript
import { page } from '@roxi/routify'

$: console.log($page.path)
```
This will log the path whenever it changes.

**Comment by MirrorBytes** [comment] 2020-09-21 19:06
I put path instead of page.... I'm way too tired right now.

Edit: $page.path is exactly what I needed.
I made a wrong assumption about $url()

**Comment by jakobrosenberg** [comment] 2020-09-21 19:07
No problem. I'll close this issue for now. 🙂

**Closed as completed by jakobrosenberg** 2020-09-21 19:07 UTC
