### ISSUE TITLE
Fix first descending animation is fade

### ISSUE THREAD

**Issue by flymedllva** [roxiness/routify#282] opened 2020-10-31 15:31 UTC
**bug description**
Hi. I like transitions using "index", but I noticed that if you refresh the web page and try to go to some other screen, the animation of collapsing the old window will not fly(a beautiful vertical transition), but the standard fade. However, the next time you click without reloading the page, everything works fine.
This problem exists in absolutely all versions of routify, including 2.3.0 and 1.9.7

**version**
https://example.routify.dev/example/transitions/tabs/feed/

**video**
[YouTube](https://youtu.be/SoEXyaFjsZg)

**Comment by jakobrosenberg** [comment] 2020-10-31 18:45
Can you elaborate on the issue? Where in the video is the problem?

**Comment by flymedllva** [comment] 2020-10-31 19:15
Try again.
1. Update the page
2. go to another page and look at the animation of the missing element. FADE
3. Go back to the page where the transition was from
4. Trying to make the transition to another page again. We see a different animation of the missing element. FLY

[YouTube](https://youtu.be/nyyWHUMTz-w)

After the page loads, the correct FLY animation should be triggered immediately

**Comment by jakobrosenberg** [comment] 2020-10-31 21:16
I see what you mean now. Any idea what the cause could be?

**Comment by flymedllva** [comment] 2020-10-31 21:44
If I had known, I would have thrown MR :)

**Comment by jakobrosenberg** [comment] 2020-11-01 19:50
Thanks for the heads up on this. The has been fixed in version `2.5.1`.

It's no longer required to specify width manually when using the TabsTransition. https://github.com/roxiness/routify-starter/commit/ed8026c1954c627b48da0a9cba173c1021de60c1

**Comment by flymedllva** [comment] 2020-11-01 19:59
I checked, it really works. Thanks!
When is the release planned?

**Comment by jakobrosenberg** [comment] 2020-11-02 06:11
Any day now. Been updating the docs. Once that is done, I'll release it.

**Closed as completed by jakobrosenberg** 2020-11-02 06:11 UTC
