### ISSUE TITLE
url parameter not fully resolved

### ISSUE THREAD

**Issue by josesan9** [roxiness/routify#346] opened 2021-03-05 15:39 UTC
**bug description**
sometimes when using `$url()`, the full url is not returned, only returning part of the url.

assume the following folder structure:
+ pages
    - _layout.svelte
    + admin
        - _layout.svelte
        - page.svelte

and the contents of all files is the following:
```
<script>
    import { url } from "@roxi/routify";
    console.log($url());
</script>
<!-- slot as well if relevant -->
```
the console output when navigating to `www.mypage.com/admin/page` will look as follows:
```
""
"/admin"
"/admin/page"
```
I can understand why this would not be incorrect, as I am assuming that the url is being resolved over time. However, I am using authentication in my layout files (roughly) as follows:
```
onMount(() => {
    if (!authenticated) {
        $goto("/login", { nextUrl: $url() });
    }
}
```
This means I am being redirected to my login, but the `nextUrl` is not set to the full resolved path.

I have tried using `afterPageLoad` instead of `onMount` but it never triggers (or at least not when travelling to the url directly).

**version**
Routify - 2.12.0
Svelte - 3.0.0

Would this be a case where I need to get the url manually? or is this a bug?
Thanks

**Comment by ghostdevv** [comment] 2021-03-30 22:50
Can you see if updating routify fixes this?

**Comment by josesan9** [comment] 2021-03-31 08:42
Hi,
I have updated to Routify 2.15.1 and the issue still persists.

**Comment by ghostdevv** [comment] 2021-04-01 16:12
I am unable to reproduce this, it could be something to do with your authentication but I doubt it. If you can't work out what is going on then you could always do something like: `$url() == '' ? '/' : $url()`, alternatively you could use something like
```js
import { page } from '@roxi/routify';
$page.path; // use this instead of the url helper
```

I will close this for now, if you are able to give me any more info that would help in reproducing then I will try it out, or if you find the cause let me know.

**Closed as completed by ghostdevv** 2021-04-01 16:12 UTC
Labels: solved
