### ISSUE TITLE
Click events broken in root _layout on build/serve

### ISSUE THREAD

**Issue by WeAreELIC** [roxiness/routify#327] opened 2021-02-01 18:09 UTC
`"@roxi/routify": "^2.8.5"`

When building and serving a site—`npm run build` and `npm run serve`—click events in the root _layout.svelte file do not work. Here's a simple example:

```svelte
<script>
  let show = false;
  
  function test() {
    console.log("TEST function");
    show = true;
  }
</script>

{#if !show}
  <button type="button" on:click="{test}">Test</button>
{:else}
  <slot />
{/if}
```

AND

`<button type="button" on:click="{() => console.log("Inline test")}">Inline Test</button>`

Neither of these functions is fired. It seems to work in layout and resets files in children folders, however.

This breaks my authentication as it's applied to the root layout file! Help!

**UPDATE:**
This appears to not work only when the `<slot />` is in the `if / else` statement

**Comment by jakobrosenberg** [comment] 2021-02-01 19:25
Could this be a Svelte issue?

**Comment by jakobrosenberg** [comment] 2021-02-01 21:12
If I copy paste your script over the original code in App.svelte it still breaks for me. In other words it still breaks if I'm using Svelte without Routify.

**Comment by WeAreELIC** [comment] 2021-02-01 21:33
So, is this a recent bug in Svelte then? According to your documentation (https://routify.dev/examples), this should work, right?

Also, does Svelte support `slots` in the App.svelte file or just in other files/components?

**Comment by jakobrosenberg** [comment] 2021-02-02 09:01
I have found the cause of your issue. It's caused by `spank`/`tossr`.

When you're using static exports (spassr, spank & tossr), the static HTML isn't generated till the page has fully loaded.

Routify emits an `app-loaded` event after it has resolved the visited page component (e.g. index.svelte), but in your case that never happens as `slot` is hidden indefinitely.

Thanks for bringing this up. I've updated the documentation to cover auth with SSR: https://routify.dev/examples/auth

I'm closing this for now, but feel free to continue the conversation. 🙂

**Closed as completed by jakobrosenberg** 2021-02-02 09:01 UTC

**Comment by WeAreELIC** [comment] 2021-02-02 17:48
Awesome, thanks so much!

**Comment by WeAreELIC** [comment] 2021-02-02 20:05
Hey, one follow-up—when doing something like this:
```svelte
<script>
  ...
  $ready()

  let showPage = false;
  
  // $user = Svelte store
  $: if ($user) {
    showPage = true;
  } else {
    showPage = false;
  }
</script>

{#if showPage}
  <!-- Page Content -->
  <div class="main">
    ...
    <slot />
  </div>
{:else}
  <!-- Login -->
  <Login {loginWithGoogle} />
{/if}
```
When I build and serve the site this works, however, if I refresh the page the login component is briefly shown before the page content. It doesn't seem to matter where the `$ready()` function is. Any ideas on how to prevent this?

Thanks, you rock!

**Comment by jakobrosenberg** [comment] 2021-02-02 20:52
The flash is caused by the user being authenticated, which happens asynchronously. 

```html
<!-- set `isAuthenticated` to true, after a potential token 
  has been checked against the authentication server -->
{#if !$user.isAuthenticated}
  <h3>Authenticating...</h3>
{:else if !$user.isGuest}
  <slot />
{:else}
  <Login {loginWithGoogle} />
{/if}
```

**Comment by WeAreELIC** [comment] 2021-02-03 15:42
This is happening when the user is already authenticated and stored in a Svelte Store and `localStorage`. So, I'm not understanding why it would flash still...thoughts? Thanks for the help!

**Comment by jakobrosenberg** [comment] 2021-02-03 16:25
I'm not sure, but it could be the reactive `$` variables. They run after your normal code.

**Comment by WeAreELIC** [comment] 2021-02-03 18:08
Even without the reactive variable, it still flashes. I've tried many different combos and it still flashes. Does the same happen for you?

**Comment by jakobrosenberg** [comment] 2021-02-03 20:21
Not that I can recall. If it flashes it's because it renders before your store is ready.
