### ISSUE TITLE
Svelte 'out' transitions cause previous page to remain on screen during page transition with $goto or $redirect

### ISSUE THREAD

**Issue by marcusnewton** [roxiness/routify#314] opened 2021-01-13 23:57 UTC
**Is your feature request related to a problem? Please describe.**
I have pages that contain elements playing various in and out transitions, and the page can be navigated away from at an arbitrary time. The problem is that these lingering transitions block the first page from being unmounted before the second page loads in.

Here is a [reprex](https://github.com/DnA-Pathways/routify-lingering-animations-repro). You can see that the text must fully fade out before the first page is removed from the DOM.

**Describe the solution you'd like**
An optional argument for `$goto` and `$redirect` to kill all transition effects on the first page to ensure that it is unmounted instantly, as the second page is mounted.

**Describe alternatives you've considered**
Appending [`|local`](https://svelte.dev/docs#Transition_events) to Svelte transition directives. May not be appropriate in all situations.

**Comment by jakobrosenberg** [comment] 2021-01-14 08:54
Hey @marcusnewton. Thanks for the reproducible. Do you know if Svelte offers a way to kill all transition effects?

Also, have you tried something like
```html
<script>
  import { fade } from "svelte/transition";
  import { beforeUrlChange } from '@roxi/routify'

  let myTransition = null
  beforeUrlChange((event, route)=>{
    myTransition = myCondition ? fade : null
  })
</script>

<h1>Page 1</h1>

<p out:myTransition={{ duration: 5000 }}>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Aut nemo magni atque
  ipsam, soluta modi. Dolor ad magni enim est. Impedit voluptates deleniti
  voluptate tenetur aliquam dolor reprehenderit accusantium architecto sequi
  libero! Quo neque cumque soluta non qui doloremque ipsum explicabo totam!
  Provident veniam perspiciatis ipsam dolore dicta labore possimus.
</p>

<button on:click={() => $goto("./page2")}>Next</button>
```
I'm not 100% sure that it's possible to change a transition after instantiation, but it's worth a try.

**Comment by marcusnewton** [comment] 2021-01-14 12:30
I had a look into any Svelte functionality for that before submitting the issue, couldn't find anything unfortunately.

I'll have a look at your proposed example but I'm not excited about transition wrappers. Using `|local` seems to be the most elegant workaround currently.

**Comment by jakobrosenberg** [comment] 2021-01-14 20:00
I'm afraid this simply boils down to the way Svelte is designed. You can try asking on the Svelte discord, but I imagine the answer is that it's by design.

I'm closing this now for now as it's not a Routify issue, but feel free to keep the conversation going.

**Closed as completed by jakobrosenberg** 2021-01-14 20:00 UTC
