### ISSUE TITLE
Apollo GraphQL: 'import' and 'export' may only appear at the top level

### ISSUE THREAD

**Issue by OllieJT** [roxiness/routify#193] opened 2020-05-27 13:25 UTC
**bug description**
I've been exploring different methods of routing in Svelte and think I want to dive deeper with Routify, but am running into blockers setting up Apollo GraphQL.

`[!] Error: 'import' and 'export' may only appear at the top level`

Starting with the Routify starter I moved over my apollo configuration files from other starters. I immediately encountered issues.

I have tried
### Dependencies
Moving apollo to dependencies (instead of devDependencies). This was the route of a sapper/rollup issue last week so I thought it was worth a shot.

### Babel
- I'm using **svelte-preprocess** for scss and babel. In the docs they recommended to not resolve modules, but I think enabling it fixed this issue. It did however also break Routify:
``` js
(!) Plugin svelte: 'Router' is not defined
src/App.svelte
34: setClient(client);</script>
35: 
36: <Router {routes} />
    ^
37: 
(!) Plugin svelte: 'routes' is not defined
src/App.svelte
34: setClient(client);</script>
35: 
36: <Router {routes} />
```

### Setup
I've added svelte-preprocess to my rollup config and apollo to my App.svelte. This was copied over from a withing [svelte-routing](https://github.com/EmilTholin/svelte-routing) setup which leads me to believe this issue is related to routify.
```html
// src/App.svelte

<script>
	import { Router } from '@sveltech/routify';
	import { routes } from '@sveltech/routify/tmp/routes';

	import fetch from 'node-fetch';
	import { ApolloClient } from 'apollo-client';
	import { createHttpLink } from 'apollo-link-http';
	import { setContext } from 'apollo-link-context';
	import { InMemoryCache } from 'apollo-cache-inmemory';

	const httpLink = new createHttpLink({
		uri: 'https://ant-venom.myshopify.com/api/graphql',
		fetch,
	});

	const middlewareLink = setContext(() => ({
		headers: {
			'X-Shopify-Storefront-Access-Token': 'f2daa4c4d566a62a58c7121e3e2265b4',
		},
	}));

	const link = middlewareLink.concat(httpLink);
	const cache = new InMemoryCache();
	const client = new ApolloClient({ link, cache });

	setClient(client);
</script>

<Router {routes} />
```
### package.json
```json
{
	"name": "svelte-app",
	"version": "1.0.0",
	"scripts": {
		"dev": "run-p routify rollup",
		"dev-dynamic": "cross-env BUNDLING=dynamic npm run dev",
		"build": "npm run routify -- -b && rollup -c",
		"serve": "spassr --serve-spa --serve-ssr",
		"export": "routify export",
		"build:docker": "npm run build && ./scripts/docker/docker-build.sh",
		"deploy:now": "cd scripts/now && npm run deploy",
		"deploy:netlify": "cd scripts/netlify && npm run deploy",
		"rollup": "rollup -cw",
		"routify": "routify -D"
	},
	"devDependencies": {
		"@babel/core": "^7.0.0",
		"@babel/plugin-syntax-dynamic-import": "^7.0.0",
		"@babel/plugin-transform-runtime": "^7.0.0",
		"@babel/preset-env": "^7.0.0",
		"@babel/runtime": "^7.0.0",
		"@rollup/plugin-commonjs": "^11.1.0",
		"@rollup/plugin-node-resolve": "^7.1.3",
		"autoprefixer": "^9.8.0",
		"concurrently": "^5.1.0",
		"cross-env": "^7.0.2",
		"del": "^5.1.0",
		"node-fetch": "^2.6.0",
		"npm-run-all": "^4.1.5",
		"ppid-changed": "^1.0.1",
		"rollup": "^2.6.1",
		"rollup-plugin-copy": "^3.3.0",
		"rollup-plugin-livereload": "^1.2.0",
		"rollup-plugin-svelte": "^5.2.1",
		"rollup-plugin-terser": "^5.3.0",
		"spassr": "^1.0.2",
		"svelte-preprocess": "^3.7.4"
	},
	"dependencies": {
		"apollo-boost": "^0.4.9",
		"apollo-cache-inmemory": "^1.6.6",
		"apollo-link-context": "^1.0.20",
		"apollo-link-http": "^1.5.17",
		"@sveltech/routify": "^1.5.9",
		"svelte-apollo": "^0.3.0",
		"svelte": "^3.20.1"
	}
}
```

**screenshot**
Sometimes they help. Extra points for good memes.
![I broke it](https://memegenerator.net/img/instances/64954469.jpg)

**Comment by mrbarletta** [comment] 2020-05-30 05:49
Just passing by and I think I know what the issue is, it is related to `"@rollup/plugin-commonjs": "^11.1.0",` and is already mentioned in sveltejs and the rollup issue tracker, downgrade and it should work!

**Comment by benmccann** [comment] 2020-06-12 03:27
I'd go the other way and upgrade to v12 or v13. The issue has since been fixed

**Comment by jakobrosenberg** [comment] 2020-06-12 06:34
I'm closing this as it has been solved here and on Discord.

**Closed as completed by jakobrosenberg** 2020-06-12 06:34 UTC
