### ISSUE TITLE
anyone can explain this error / 'ERR_INVALID_ARG_TYPE' ?

### ISSUE THREAD

**Issue by realwesen** [roxiness/routify#350] opened 2021-03-15 06:51 UTC
When I do `yarn build` then `yarn serve`,
following error occurs.

```
[tossr] /@david - 549ms
node:buffer:202
    throw new ERR_INVALID_ARG_TYPE('target', ['Buffer', 'Uint8Array'], target);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "target" argument must be an instance of Buffer or Uint8Array. Received null
    at new NodeError (node:internal/errors:329:5)
    at _copy (node:buffer:202:11)
    at Buffer.copy (node:buffer:776:12)
    at Request.<anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:864:11)
    at Request.emit (node:events:378:20)
    at Gunzip.<anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/request/request.js:1073:12)
    at Gunzip.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Gunzip.Readable.push (node:internal/streams/readable:227:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

the website works, but not always.

please refer following page.

[link](https://dev-07--allius-dev.netlify.app/@david)

**Comment by jakobrosenberg** [comment] 2021-03-15 07:49
Hi @realwesen, do you know what page causes the issue and would it be possible to see the source code?

**Comment by realwesen** [comment] 2021-03-15 08:26
@jakobrosenberg I gave you access to https://github.com/realwesen/allius-routify/tree/develop
and the url is `src/@[userId]/index.svelte`.
@seongto in discord is me !

**Comment by jakobrosenberg** [comment] 2021-03-16 17:27
I was unable to reproduce the error. The page is loading fine for me and so is the source code. Could it be flaky API?

**Comment by realwesen** [comment] 2021-03-17 02:26
The page is loading fine for me too, but the error occurs randomly. I don't know about  flaky API.
Do you checking `develop` branch?

[please check this page ](https://allius-dev.netlify.app/@david)

sometimes, the error occurs like this,
```
TypeError: Cannot read property 'createElement' of undefined
    at k (eval at <anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/tossr/tossr.js:96:24), <anonymous>:2134:21)
    at Object.c (eval at <anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/tossr/tossr.js:96:24), <anonymous>:3998:12)
    at Object.c (eval at <anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/tossr/tossr.js:96:24), <anonymous>:3974:16)
    at Object.p (eval at <anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/tossr/tossr.js:96:24), <anonymous>:4021:81)
    at oe2 (eval at <anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/tossr/tossr.js:96:24), <anonymous>:2278:51)
    at ne3 (eval at <anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/tossr/tossr.js:96:24), <anonymous>:2259:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
or
```
throw new ERR_INVALID_ARG_TYPE('target', ['Buffer', 'Uint8Array'], target);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "target" argument must be an instance of Buffer or Uint8Array. Received null
    at new NodeError (node:internal/errors:329:5)
    at _copy (node:buffer:202:11)
    at Buffer.copy (node:buffer:776:12)
    at Request.<anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:864:11)
    at Request.emit (node:events:378:20)
    at Gunzip.<anonymous> (/Users/seongto/devs/front-end/f14-allius-public-routify/node_modules/request/request.js:1073:12)
    at Gunzip.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Gunzip.Readable.push (node:internal/streams/readable:227:10) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

at that moment, this is error message on console (Chrome).
`GET https://allius-dev.netlify.app/@david 502`

Network check :

general
```
Request URL: https://allius-dev.netlify.app/@david
Request Method: GET
Status Code: 502 
Remote Address: 178.128.93.124:443
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by jakobrosenberg** [comment] 2021-03-17 06:35
Looking at `XMLHttpRequest-impl.js:864:11`, I'm fairly sure that this is caused by a bad endpoint.

https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/xhr/XMLHttpRequest-impl.js#L864

Where are you hosting your site?

**Comment by realwesen** [comment] 2021-03-17 10:19
but the endpoint is working well. Even when the error occurred, API request was successful.
I'm using 2 backend, one is on aws lambda, the other one is on firebase. 

all endpoints of `https://allius-dev.netlify.app/@david` are on firebase.

**Comment by ghostdevv** [comment] 2021-03-30 22:49
Are you still having this issue? @realwesen if so @jakobrosenberg can follow up

**Comment by realwesen** [comment] 2021-04-05 02:13
@ghostdevv yes, I'm still having the problem.

**Comment by jakobrosenberg** [comment] 2021-04-06 07:24
If it happens randomly, but the compiled code is static, it sounds like something isn't working outside of the compiled code. Combined with the error you're getting, everything is pointing at an unreliable endpoint.

I'm closing this for now, but I'll be happy to help you with this if you can create minimal reproducible example. However with the current info, I can't do much more than guess at what's causing the error.

**Closed as completed by jakobrosenberg** 2021-04-06 07:24 UTC
Labels: not routify
